CREATE SCHEMA IF NOT EXISTS `myDb` DEFAULT CHARACTER SET utf8;
USE `myDb`;

CREATE TABLE IF NOT EXISTS `myDb`.`products` (
  `id` VARCHAR NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `valueItem` VARCHAR(255) NOT NULL,
  `quantity` TINYINT NULL DEFAULT 1,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `myDb`.`users` (
  `id` VARCHAR NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;